### PR TITLE
Include Folder + typos

### PR DESCRIPTION
**Pull request by xZevalx**
Solved #23 and #15 .

Now exists a folder to contain Include Files, all of them should be stored there!
There are two for default "IncludeFile-EMI_PM10.py" and "IncludeFile.py.WRF". 

The first time you run mospat_main.py the system lists the content of IncludeFolder and let you choose a IncludeFile to use it as default for current and future executions.

The system creates a symlink that appers in MOSPAT's root directory so you can modify it without problems.

The gitignore file is configured to ignore everything in IncludeFolder but the defaults files. It also ignores the symlink, so you can make "git push" without taking care of it.

If you want to change your IncludeFile to another one you have two ways:
- Use rm for both "IncludeFile.py" and "IncludeFile.pyc" in MOSPAT's root and the system will let you choose a new one next time you run it.
- Override the current symlink by yourself.

### CODE REVIEW

**Comment by ceordonez** [comment]
@xZevalx The file RunAnalysis.job is needed to run in other partitions of the cluster and please remove the IncludeFile.pyc from the "standard" repository.

**Comment by xZevalx** [comment]
@ceordonez RunPythonAnalisis.sh is also needed?
On the other hand, the file IncludeFile.pyc is not under tracing, what do you mean with removing it?

**Comment by ceordonez** [comment]
@xZevalx The RunPythonAnalisis.sh is not needed. Regarding IncludeFile.pyc... my mistake! sorry.

**Comment by xZevalx** [comment]
Done :+1:

**Pull request merged**
